# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nQNBNam1hwgNaeye63gDQYLQnNXh5pkN
"""

# -*- coding: utf-8 -*-
"""
AI MEDICAL PRESCRIPTION VERIFICATION SYSTEM
Fixed Version - All Type Errors Resolved
"""

print("=" * 70)
print("AI MEDICAL PRESCRIPTION VERIFICATION SYSTEM")
print("=" * 70)
print("\nStarting installation...\n")

# ===== INSTALLATION =====
import subprocess
import sys
import os

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

def install(package):
    try:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", package])
    except:
        pass

print("Installing packages...")
packages = ["gradio", "deep-translator"]
for pkg in packages:
    install(pkg)

print("Installation complete!\n")

# ===== IMPORTS =====
import gradio as gr
import re
from typing import List, Dict
from deep_translator import GoogleTranslator
import warnings
warnings.filterwarnings('ignore')

print("Imports successful!\n")

# ===== DRUG DATABASE =====
DRUG_DATABASE = {
    "aspirin": {
        "name": "Aspirin",
        "category": "NSAID",
        "interactions": ["warfarin", "ibuprofen", "clopidogrel"],
        "dosage": {"adult": "325-650mg every 4-6 hours", "child": "10-15mg/kg every 4-6 hours", "elderly": "325mg daily"},
        "contraindications": ["bleeding disorders", "ulcers"],
        "alternatives": ["acetaminophen", "paracetamol"]
    },
    "paracetamol": {
        "name": "Paracetamol",
        "category": "Analgesic",
        "interactions": ["warfarin", "alcohol"],
        "dosage": {"adult": "500-1000mg every 4-6 hours", "child": "10-15mg/kg every 4-6 hours", "elderly": "500mg every 6 hours"},
        "contraindications": ["liver disease"],
        "alternatives": ["ibuprofen", "aspirin"]
    },
    "ibuprofen": {
        "name": "Ibuprofen",
        "category": "NSAID",
        "interactions": ["aspirin", "warfarin", "lithium"],
        "dosage": {"adult": "200-400mg every 4-6 hours", "child": "5-10mg/kg every 6-8 hours", "elderly": "200mg every 8 hours"},
        "contraindications": ["kidney disease", "heart disease"],
        "alternatives": ["naproxen", "acetaminophen"]
    },
    "metformin": {
        "name": "Metformin",
        "category": "Antidiabetic",
        "interactions": ["alcohol", "contrast dye"],
        "dosage": {"adult": "500-1000mg twice daily", "child": "Not recommended", "elderly": "500mg once daily"},
        "contraindications": ["kidney disease", "liver disease"],
        "alternatives": ["glipizide", "sitagliptin"]
    },
    "warfarin": {
        "name": "Warfarin",
        "category": "Anticoagulant",
        "interactions": ["aspirin", "ibuprofen", "vitamin k", "amoxicillin"],
        "dosage": {"adult": "2-10mg daily", "child": "Consult specialist", "elderly": "Lower dose required"},
        "contraindications": ["pregnancy", "bleeding disorders"],
        "alternatives": ["apixaban", "rivaroxaban"]
    },
    "lisinopril": {
        "name": "Lisinopril",
        "category": "ACE Inhibitor",
        "interactions": ["potassium supplements", "nsaids"],
        "dosage": {"adult": "10-40mg once daily", "child": "Not recommended", "elderly": "5-10mg once daily"},
        "contraindications": ["pregnancy", "angioedema"],
        "alternatives": ["losartan", "valsartan"]
    },
    "amlodipine": {
        "name": "Amlodipine",
        "category": "Calcium Channel Blocker",
        "interactions": ["simvastatin", "grapefruit juice"],
        "dosage": {"adult": "5-10mg once daily", "child": "Not recommended", "elderly": "2.5-5mg once daily"},
        "contraindications": ["severe aortic stenosis"],
        "alternatives": ["nifedipine", "diltiazem"]
    },
    "omeprazole": {
        "name": "Omeprazole",
        "category": "Proton Pump Inhibitor",
        "interactions": ["clopidogrel", "digoxin"],
        "dosage": {"adult": "20-40mg once daily", "child": "0.5-1mg/kg once daily", "elderly": "20mg once daily"},
        "contraindications": ["hypersensitivity"],
        "alternatives": ["pantoprazole", "esomeprazole"]
    },
    "amoxicillin": {
        "name": "Amoxicillin",
        "category": "Antibiotic",
        "interactions": ["methotrexate", "warfarin"],
        "dosage": {"adult": "250-500mg every 8 hours", "child": "20-40mg/kg/day", "elderly": "250mg every 8 hours"},
        "contraindications": ["penicillin allergy"],
        "alternatives": ["azithromycin", "cephalexin"]
    },
    "atorvastatin": {
        "name": "Atorvastatin",
        "category": "Statin",
        "interactions": ["grapefruit juice", "gemfibrozil"],
        "dosage": {"adult": "10-80mg once daily", "child": "Not recommended", "elderly": "10-20mg once daily"},
        "contraindications": ["liver disease", "pregnancy"],
        "alternatives": ["rosuvastatin", "simvastatin"]
    }
}

print("Drug database loaded\n")

# ===== NLP SYSTEM =====
class MedicalNLP:
    def __init__(self):
        self.drug_names = list(DRUG_DATABASE.keys())

    def extract_medications(self, text):
        if not text:
            return []

        text_lower = text.lower()
        medications = []
        found_drugs = set()

        for drug_key in self.drug_names:
            if drug_key in text_lower:
                found_drugs.add(drug_key)

        for drug_key in found_drugs:
            dosage = self.extract_dosage(text_lower, drug_key)
            frequency = self.extract_frequency(text_lower, drug_key)

            medications.append({
                "name": drug_key,
                "display_name": DRUG_DATABASE[drug_key]["name"],
                "dosage": dosage,
                "frequency": frequency
            })

        return medications

    def extract_dosage(self, text, drug):
        patterns = [
            rf'{drug}\s*(\d+(?:\.\d+)?\s*(?:mg|g|ml|mcg))',
            rf'(\d+(?:\.\d+)?\s*(?:mg|g|ml|mcg))\s*{drug}'
        ]

        for pattern in patterns:
            match = re.search(pattern, text)
            if match:
                return match.group(1).strip()

        return "As prescribed"

    def extract_frequency(self, text, drug):
        patterns = [
            r'(once|twice|three times)\s*(?:a\s+)?(?:day|daily)',
            r'every\s*(\d+)\s*hours',
            r'(\d+)\s*times?\s*(?:per\s+)?(?:day|daily)'
        ]

        for pattern in patterns:
            match = re.search(pattern, text)
            if match:
                return match.group(0)

        return "As directed"

nlp_system = MedicalNLP()
print("NLP system ready\n")

# ===== CORE FUNCTIONS =====

def translate_text(text, target_lang):
    """Translate text to target language"""
    if not text or target_lang == 'en':
        return text
    try:
        translated = GoogleTranslator(source='en', target=target_lang).translate(text[:4500])
        return translated
    except Exception as e:
        print(f"Translation error: {e}")
        return text

def extract_drugs(prescription_text):
    """Extract medications from prescription text"""
    return nlp_system.extract_medications(prescription_text)

def detect_interactions(drugs):
    """Detect drug interactions"""
    interactions = []
    drugs_clean = [d.lower().strip() for d in drugs]

    for i, drug1 in enumerate(drugs_clean):
        if drug1 in DRUG_DATABASE:
            for drug2 in drugs_clean[i+1:]:
                if drug2 in DRUG_DATABASE[drug1]["interactions"]:
                    interactions.append({
                        "drug1": DRUG_DATABASE[drug1]["name"],
                        "drug2": DRUG_DATABASE.get(drug2, {}).get("name", drug2),
                        "severity": "WARNING",
                        "description": f"Interaction between {DRUG_DATABASE[drug1]['name']} and {drug2}"
                    })

    return interactions

def get_age_dosage(drug, age):
    """Get age-specific dosage recommendations"""
    drug_lower = drug.lower().strip()

    if drug_lower not in DRUG_DATABASE:
        return {
            "drug": drug,
            "age_group": "Unknown",
            "recommended_dosage": "Consult physician",
            "category": "Unknown"
        }

    drug_info = DRUG_DATABASE[drug_lower]

    if age < 12:
        age_group = "child"
    elif age >= 65:
        age_group = "elderly"
    else:
        age_group = "adult"

    return {
        "drug": drug_info["name"],
        "age_group": age_group.capitalize(),
        "recommended_dosage": drug_info["dosage"].get(age_group, "Consult physician"),
        "category": drug_info["category"]
    }

def get_alternatives(drug):
    """Get alternative medications"""
    drug_lower = drug.lower().strip()
    if drug_lower in DRUG_DATABASE:
        return DRUG_DATABASE[drug_lower]["alternatives"]
    return ["Consult physician"]

def analyze_prescription(prescription_text, patient_age, language):
    """Main analysis function - FIXED VERSION"""
    try:
        # Input validation
        if not prescription_text or not prescription_text.strip():
            return (
                "Please enter prescription text",
                "",
                "",
                ""
            )

        # Extract drugs
        extracted_drugs = extract_drugs(prescription_text)

        if not extracted_drugs:
            return (
                "No medications detected in the prescription text",
                "No medications found",
                "",
                ""
            )

        # Get drug names and analyze
        drug_names = [d["name"] for d in extracted_drugs]
        interactions = detect_interactions(drug_names)
        dosages = [get_age_dosage(drug, patient_age) for drug in drug_names]

        # Get alternatives for interacting drugs
        alternatives = {}
        if interactions:
            for inter in interactions:
                drug_lower = inter["drug1"].lower()
                if drug_lower in DRUG_DATABASE:
                    alternatives[inter["drug1"]] = get_alternatives(drug_lower)

        # BUILD SUMMARY OUTPUT
        summary_lines = []
        summary_lines.append("=" * 60)
        summary_lines.append("PRESCRIPTION ANALYSIS REPORT")
        summary_lines.append("=" * 60)
        summary_lines.append(f"Patient Age: {patient_age} years")
        summary_lines.append(f"Total Medications: {len(extracted_drugs)}")
        summary_lines.append("")

        if interactions:
            summary_lines.append(f"⚠️  WARNING: {len(interactions)} DRUG INTERACTION(S) DETECTED")
            summary_lines.append("-" * 60)
            for idx, inter in enumerate(interactions, 1):
                summary_lines.append(f"{idx}. {inter['drug1']} + {inter['drug2']}")
                summary_lines.append(f"   {inter['description']}")
            summary_lines.append("")
        else:
            summary_lines.append("✓ No significant interactions detected")
            summary_lines.append("")

        if dosages:
            summary_lines.append("AGE-SPECIFIC DOSAGE RECOMMENDATIONS")
            summary_lines.append("-" * 60)
            for dosage in dosages:
                summary_lines.append(f"• {dosage['drug']} ({dosage['category']})")
                summary_lines.append(f"  Age Group: {dosage['age_group']}")
                summary_lines.append(f"  Recommended: {dosage['recommended_dosage']}")
                summary_lines.append("")

        if alternatives:
            summary_lines.append("ALTERNATIVE MEDICATIONS")
            summary_lines.append("-" * 60)
            for drug, alts in alternatives.items():
                summary_lines.append(f"Instead of {drug}: {', '.join(alts)}")
            summary_lines.append("")

        summary_lines.append("=" * 60)
        summary_lines.append("⚕️  DISCLAIMER: Consult healthcare professional")
        summary_lines.append("=" * 60)

        summary_text = "\n".join(summary_lines)

        # BUILD DRUGS OUTPUT
        drugs_lines = []
        drugs_lines.append("EXTRACTED MEDICATIONS")
        drugs_lines.append("=" * 40)
        drugs_lines.append("")
        for idx, drug in enumerate(extracted_drugs, 1):
            drugs_lines.append(f"{idx}. {drug['display_name']}")
            drugs_lines.append(f"   Dosage: {drug['dosage']}")
            drugs_lines.append(f"   Frequency: {drug['frequency']}")
            drugs_lines.append("")
        drugs_text = "\n".join(drugs_lines)

        # BUILD INTERACTIONS OUTPUT
        if interactions:
            inter_lines = []
            inter_lines.append("⚠️  DRUG INTERACTIONS WARNING")
            inter_lines.append("=" * 40)
            inter_lines.append("")
            for idx, inter in enumerate(interactions, 1):
                inter_lines.append(f"{idx}. {inter['drug1']} ⚠️  {inter['drug2']}")
                inter_lines.append(f"   Severity: {inter['severity']}")
                inter_lines.append(f"   {inter['description']}")
                inter_lines.append("")
            interactions_text = "\n".join(inter_lines)
        else:
            interactions_text = "✓ No interactions detected"

        # BUILD ALTERNATIVES OUTPUT
        if alternatives:
            alt_lines = []
            alt_lines.append("ALTERNATIVE MEDICATIONS")
            alt_lines.append("=" * 40)
            alt_lines.append("")
            for drug, alts in alternatives.items():
                alt_lines.append(f"Instead of {drug}:")
                for alt in alts:
                    alt_lines.append(f"  • {alt}")
                alt_lines.append("")
            alternatives_text = "\n".join(alt_lines)
        else:
            alternatives_text = "No alternatives needed"

        # Translate if needed
        if language != "en":
            summary_text = translate_text(summary_text, language)
            drugs_text = translate_text(drugs_text, language)
            interactions_text = translate_text(interactions_text, language)
            alternatives_text = translate_text(alternatives_text, language)

        # Return all strings
        return (
            summary_text,
            drugs_text,
            interactions_text,
            alternatives_text
        )

    except Exception as e:
        error_msg = f"Error: {str(e)}"
        print(error_msg)
        return (
            error_msg,
            "Error processing",
            "Error processing",
            "Error processing"
        )

# ===== GRADIO INTERFACE =====

print("Building interface...\n")

def create_interface():
    with gr.Blocks(theme=gr.themes.Soft(), title="AI Medical Prescription Verification") as demo:

        gr.Markdown("""
        # 🏥 AI Medical Prescription Verification System
        ### Intelligent Drug Analysis and Safety Checker

        **Features:**
        - 💊 Drug Interaction Detection
        - 👶👴 Age-Specific Dosage Recommendations
        - 🔄 Alternative Medication Suggestions
        - 🤖 AI-Powered Prescription Analysis
        - 🌍 Multi-Language Support
        """)

        with gr.Row():
            with gr.Column():
                prescription_input = gr.Textbox(
                    label="📝 Enter Prescription Text",
                    placeholder="Example: Patient prescribed Aspirin 325mg twice daily and Ibuprofen 400mg three times daily",
                    lines=10
                )

                age_input = gr.Slider(
                    minimum=1,
                    maximum=120,
                    value=45,
                    step=1,
                    label="👤 Patient Age"
                )

                language_input = gr.Dropdown(
                    choices=[
                        ("English", "en"),
                        ("Hindi", "hi"),
                        ("Tamil", "ta"),
                        ("Telugu", "te"),
                        ("Bengali", "bn"),
                        ("Marathi", "mr"),
                        ("Gujarati", "gu")
                    ],
                    value="en",
                    label="🌐 Output Language"
                )

                analyze_btn = gr.Button("🔍 Analyze Prescription", variant="primary", size="lg")

            with gr.Column():
                summary_output = gr.Textbox(label="📊 Analysis Summary", lines=14)

        with gr.Row():
            drugs_output = gr.Textbox(label="💊 Extracted Drugs", lines=8)
            interactions_output = gr.Textbox(label="⚠️ Interactions", lines=8)

        with gr.Row():
            alternatives_output = gr.Textbox(label="🔄 Alternatives", lines=6)

        gr.Markdown("""
        ### ⚕️ Medical Disclaimer
        This tool is for educational purposes only. Always consult qualified healthcare professionals.

        ### 📋 Sample Prescriptions for Testing:
        - **Test 1:** Aspirin 325mg twice daily and Ibuprofen 400mg three times daily (Age: 45)
        - **Test 2:** Metformin 500mg twice daily and Lisinopril 10mg once daily (Age: 60)
        - **Test 3:** Warfarin 5mg daily and Amoxicillin 500mg three times daily (Age: 55)
        """)

        gr.Examples(
            examples=[
                ["Patient prescribed Aspirin 325mg twice daily and Ibuprofen 400mg three times daily", 45, "en"],
                ["Metformin 500mg twice daily and Lisinopril 10mg once daily", 60, "en"],
                ["Warfarin 5mg daily and Amoxicillin 500mg three times daily", 55, "en"],
            ],
            inputs=[prescription_input, age_input, language_input]
        )

        analyze_btn.click(
            fn=analyze_prescription,
            inputs=[prescription_input, age_input, language_input],
            outputs=[summary_output, drugs_output, interactions_output, alternatives_output]
        )

    return demo

demo = create_interface()

print("=" * 70)
print("✓ SYSTEM READY!")
print("=" * 70)
print("\nLaunching application...\n")

demo.launch(share=True, debug=False)

print("\n✓ Application launched successfully!")